###
GET http://localhost:8080/common/duplicate-email
Content-Type: application/json

{
  "email": "kgulr0517@gmail.com"
}

###
GET http://localhost:8080/common/duplicate-email
Content-Type: application/json

{
  "email": "aaa@naver.com"
}

###
POST http://localhost:8080/common/send-verification-code
Content-Type: application/json

{
  "email": "kgulr0517@gmail.com"
}

###
GET http://localhost:8080/common/verify-email
Content-Type: application/json

{
  "email": "kgulr0517@gmail.com",
  "verificationCode": "4B1@s8"
}

###
POST http://localhost:8080/common/email/password
Content-Type: application/json

{
  "email": "kgulr0517@naver.com",
  "name": "임규리"
}