### create job posting test
POST http://localhost:8080/companies/56908b4bf2284fccaefc8c690ea3f440/job-postings
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb21wYW55QG5hdmVyLmNvbSIsInJvbGUiOiJST0xFX0NPTVBBTlkiLCJpYXQiOjE3MjAyNzM0MzIsImV4cCI6MTcyMDI3NzAzMn0._wtdo9Fuj4QgAk8e7yXtxJhC52CfOgnZuR9z1SoNaZo
Content-Type: application/json

{
  "title": "공고제목",
  "jobCategory": "백엔드",
  "career": "3",
  "techStack": [
    "JAVA",
    "SPRING"
  ],
  "jobPostingStep": [
    "서류단계",
    "최종면접"
  ],
  "workLocation": "서울특별시",
  "education": "4년제",
  "employmentType": "비정규직",
  "salary": 3000,
  "workTime": "09:00 ~ 15:00",
  "startDateTime": "2023-03-05",
  "endDateTime": "2023-03-15",
  "jobPostingContent": "내용"
}