### create job posting test
POST http://localhost:8080/companies/eefae5c7f8044dcab3dc0711b8c4a1c3/job-postings
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb21wYW55QG5hdmVyLmNvbSIsInJvbGUiOiJST0xFX0NPTVBBTlkiLCJpYXQiOjE3MjAyNjQyMDEsImV4cCI6MTcyMDI2NzgwMX0.xG65fphL2jRJh1XnIDu8_GVRVSlAtVYm-HjB5Dk6Upg
Content-Type: application/json

{
  "title": "공고제목",
  "jobCategory": "백엔드",
  "career": "3",
  "techStack": [
    "JAVA",
    "SPRING"
  ],
  "jobPostingStep": [
    "서류단계",
    "최종면접"
  ],
  "workLocation": "서울특별시",
  "education": "4년제",
  "employmentType": "비정규직",
  "salary": 3000,
  "workTime": "09:00 ~ 15:00",
  "startDateTime": "2023-03-05",
  "endDateTime": "2023-03-15",
  "jobPostingContent": "내용"
}