
###
POST http://localhost:8080/candidates/signup
Content-Type: application/json

{
  "name": "임규리",
  "email": "kgulr0000@naver.com",
  "verificationCode": "aa",
  "password": "!JEi2ofj3",
  "phoneNumber": "010-0000-1111"
}

###
POST http://localhost:8080/common/signin
Content-Type: application/json

{
  "email": "kgulr0000@naver.com",
  "password": "!JEi2ofj3"
}

### 지원하기
POST http://localhost:8080/candidate/job-postings/76f2d0c0f4c1424e92976035dedb9ce8/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZ3VscjAwMDBAbmF2ZXIuY29tIiwicm9sZSI6IlJPTEVfQ0FORElEQVRFIiwiaWF0IjoxNzIwNTI3MTAwLCJleHAiOjE3MjA1MzA3MDB9.puaYDykl97nfOivOWaBimCou6OGbgUNTpWH_xRJXM6Q


### 면접일정 생성 test
POST http://localhost:8080/job-postings/da152dbd5b7b4d3ea0d6652fa830c606/steps/2/interview-schedule
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjb21wYW55QG5hdmVyLmNvbSIsInJvbGUiOiJST0xFX0NPTVBBTlkiLCJpYXQiOjE3MjA5NjQ1NTUsImV4cCI6MTcyMDk2ODE1NX0.4vyNX139yKEfsRRZoNQ5Sy62FjLkBPof2NqLqtN2gMc
Content-Type: application/json

[
  {
    "startDate": "2024-06-05",
    "startTime": "14:00",
    "term": "30",
    "times": 5
  },
  {
    "startDate": "2024-06-06",
    "startTime": "14:00",
    "term": "30",
    "times": 5
  }
]