
###
POST http://localhost:8080/candidates/signup
Content-Type: application/json

{
  "name": "임규리",
  "email": "kgulr0517@naver.com",
  "verificationCode": "aa",
  "password": "!JEi2ofj3",
  "phoneNumber": "010-1111-1111"
}

###
POST http://localhost:8080/common/signin
Content-Type: application/json

{
  "email": "kgulr0517@naver.com",
  "password": "Sw6!uWPAKV4b"
}
